package com.servexa.notification.model;

public enum NotificationType {
    APPOINTMENT_REMINDER,
    APPOINTMENT_CONFIRMATION,
    APPOINTMENT_CANCELLATION,
    APPOINTMENT_RESCHEDULED,
    SERVICE_COMPLETED,
    PAYMENT_REMINDER,
    PAYMENT_RECEIVED,
    PROMOTION,
    SYSTEM,
    EMERGENCY,
    FEEDBACK_REQUEST,
    VEHICLE_SERVICE_DUE,
    VEHICLE_ADDED,
    INFO
}